### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by jadsongmatos** [poef/json-css#2]
exemplo não está funcionando

![image](https://user-images.githubusercontent.com/50336793/86503213-463ca880-bd82-11ea-9861-1452e24eb51a.png)

**Comment by poef** [comment]
It looks like you are running the example from your D: drive. Javascript is highly restricted when not running from a webserver. Please install a webserver and try to run the example using that. Alternatively, use something like codepen.io or repl.it.

**Comment by jadsongmatos** [comment]
Obrigado, deu certo agora
